version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
